theme: jekyll-theme-minimal
title: Technicat LLC
description: software in sunny Las Vegas
show_downloads: false
logo: /images/icons/cat/catglasses.svg
appstore: https://apps.apple.com/us/developer/technicat-llc/id295241742
steam: https://store.steampowered.com/app/847530/HyperBowl/
privacy: We take no data and leave no cookies
domain: technicat.com
copyright: Technicat LLC
