theme: jekyll-theme-minimal
title: Technicat LLC
description: Software development, self-publishing, and consulting in very sunny Las Vegas.
show_downloads: false
logo: /images/dakotasnow/CatGraphic300x300.jpg
